name: Build image andPush to Google

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: docker build . --tag us-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/api/v1:latest

    - name: Authenticate
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'authenticate'
      run: gcloud auth configure-docker us-east1-docker.pkg.dev

    - name: Push Docker image to Google Container Registry
      run: |-
        docker push us-east1-docker.pkg.dev/${{ secrets.GCP_ID }}/api/v1:latest