name: Deploy to App Engine

on:
  push:
    branches: main

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - name : checkout
        uses: actions/checkout@v2

      - name: Create Environment Variables
        run: |
          echo "GIPHY_KEY=${{secrets.GIPHY_KEY}}" >> ${{github.workspace}}/.env &&
          echo "REDIS_DB=${{secrets.REDIS_DB}}" >> ${{github.workspace}}/.env &&
          echo "IP_INFO_TOKEN=${{secrets.IP_INFO_TOKEN}}" >> ${{github.workspace}}/.env
      
      - name: authenticate    
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name : deploy
        run : gcloud app deploy --quiet